# Generated by Django 4.2.15 on 2024-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that Email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
