# Generated by Django 4.2.15 on 2024-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
